name = "mine"
compatibility_date = "2025-10-10"

[[d1_databases]]
binding = "DB"
database_name = "mine-db"  # نام D1 bucketت
database_id = "uuid-db-id"  # از داشبورد D1 کپی کن

[[kv_namespaces]]
binding = "KV_ORDERS"
id = "uuid-kv-id"  # از داشبورد KV کپی کن
preview_id = "uuid-preview"  # اختیاری برای preview

[env.production.vars]
TELEGRAM_TOKEN = "your_token"
ADMIN_CHAT_ID = "your_chat_id"
RESEND_API_KEY = "your_key"
ADMIN_PASSWORD = "adminpass2025"
TRONSCAN_API_KEY = "your_key"
