name = "supertrend-worker-fa"
main = "worker-fa.js"
compatibility_date = "2025-10-14"  # تاریخ فعلی

format = "modules"  # کلیدی برای ES Module

[[d1_databases]]
binding = "contact"  # نام binding: env.contact
database_name = "your-db-name"  # از D1 Dashboard
database_id = "your-db-id"      # از D1 Dashboard

# KV اگر لازم (برای orders)
[[kv_namespaces]]
binding = "KV_ORDERS"
id = "your-kv-id"  # از KV Dashboard
preview_id = "your-kv-preview-id"

# Env variables (در Dashboard تنظیم کنید یا secrets.toml)
[vars]
TELEGRAM_TOKEN = "your-telegram-bot-token"
ADMIN_CHAT_ID = "your-admin-chat-id"
RESEND_API_KEY = "your-resend-api-key"
ADMIN_PASSWORD = "adminpass2025"
TRONSCAN_API_KEY = "your-tronscan-api-key"
